// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pushable.proto

package com.landonpatmore.models;

public final class Pushable {
  private Pushable() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GeneralOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.landonpatmore.models.General)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 trackId = 2;</code>
     * @return Whether the trackId field is set.
     */
    boolean hasTrackId();
    /**
     * <code>optional int32 trackId = 2;</code>
     * @return The trackId.
     */
    int getTrackId();

    /**
     * <code>optional string trackConfigName = 3;</code>
     * @return Whether the trackConfigName field is set.
     */
    boolean hasTrackConfigName();
    /**
     * <code>optional string trackConfigName = 3;</code>
     * @return The trackConfigName.
     */
    java.lang.String getTrackConfigName();
    /**
     * <code>optional string trackConfigName = 3;</code>
     * @return The bytes for trackConfigName.
     */
    com.google.protobuf.ByteString
        getTrackConfigNameBytes();

    /**
     * <code>optional int32 numTurns = 4;</code>
     * @return Whether the numTurns field is set.
     */
    boolean hasNumTurns();
    /**
     * <code>optional int32 numTurns = 4;</code>
     * @return The numTurns.
     */
    int getNumTurns();

    /**
     * <code>optional int32 pitSpeedLimit = 5;</code>
     * @return Whether the pitSpeedLimit field is set.
     */
    boolean hasPitSpeedLimit();
    /**
     * <code>optional int32 pitSpeedLimit = 5;</code>
     * @return The pitSpeedLimit.
     */
    int getPitSpeedLimit();

    /**
     * <code>repeated float sectors = 6;</code>
     * @return A list containing the sectors.
     */
    java.util.List<java.lang.Float> getSectorsList();
    /**
     * <code>repeated float sectors = 6;</code>
     * @return The count of sectors.
     */
    int getSectorsCount();
    /**
     * <code>repeated float sectors = 6;</code>
     * @param index The index of the element to return.
     * @return The sectors at the given index.
     */
    float getSectors(int index);

    /**
     * <code>optional float totalTime = 7;</code>
     * @return Whether the totalTime field is set.
     */
    boolean hasTotalTime();
    /**
     * <code>optional float totalTime = 7;</code>
     * @return The totalTime.
     */
    float getTotalTime();
  }
  /**
   * Protobuf type {@code com.landonpatmore.models.General}
   */
  public static final class General extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.landonpatmore.models.General)
      GeneralOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use General.newBuilder() to construct.
    private General(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private General() {
      name_ = "";
      trackConfigName_ = "";
      sectors_ = emptyFloatList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new General();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private General(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              name_ = s;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              trackId_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              trackConfigName_ = s;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              numTurns_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              pitSpeedLimit_ = input.readInt32();
              break;
            }
            case 53: {
              if (!((mutable_bitField0_ & 0x00000020) != 0)) {
                sectors_ = newFloatList();
                mutable_bitField0_ |= 0x00000020;
              }
              sectors_.addFloat(input.readFloat());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000020) != 0) && input.getBytesUntilLimit() > 0) {
                sectors_ = newFloatList();
                mutable_bitField0_ |= 0x00000020;
              }
              while (input.getBytesUntilLimit() > 0) {
                sectors_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 61: {
              bitField0_ |= 0x00000020;
              totalTime_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) != 0)) {
          sectors_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.landonpatmore.models.Pushable.internal_static_com_landonpatmore_models_General_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.landonpatmore.models.Pushable.internal_static_com_landonpatmore_models_General_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.landonpatmore.models.Pushable.General.class, com.landonpatmore.models.Pushable.General.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRACKID_FIELD_NUMBER = 2;
    private int trackId_;
    /**
     * <code>optional int32 trackId = 2;</code>
     * @return Whether the trackId field is set.
     */
    @java.lang.Override
    public boolean hasTrackId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 trackId = 2;</code>
     * @return The trackId.
     */
    @java.lang.Override
    public int getTrackId() {
      return trackId_;
    }

    public static final int TRACKCONFIGNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object trackConfigName_;
    /**
     * <code>optional string trackConfigName = 3;</code>
     * @return Whether the trackConfigName field is set.
     */
    @java.lang.Override
    public boolean hasTrackConfigName() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string trackConfigName = 3;</code>
     * @return The trackConfigName.
     */
    @java.lang.Override
    public java.lang.String getTrackConfigName() {
      java.lang.Object ref = trackConfigName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        trackConfigName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string trackConfigName = 3;</code>
     * @return The bytes for trackConfigName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTrackConfigNameBytes() {
      java.lang.Object ref = trackConfigName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        trackConfigName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMTURNS_FIELD_NUMBER = 4;
    private int numTurns_;
    /**
     * <code>optional int32 numTurns = 4;</code>
     * @return Whether the numTurns field is set.
     */
    @java.lang.Override
    public boolean hasNumTurns() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 numTurns = 4;</code>
     * @return The numTurns.
     */
    @java.lang.Override
    public int getNumTurns() {
      return numTurns_;
    }

    public static final int PITSPEEDLIMIT_FIELD_NUMBER = 5;
    private int pitSpeedLimit_;
    /**
     * <code>optional int32 pitSpeedLimit = 5;</code>
     * @return Whether the pitSpeedLimit field is set.
     */
    @java.lang.Override
    public boolean hasPitSpeedLimit() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 pitSpeedLimit = 5;</code>
     * @return The pitSpeedLimit.
     */
    @java.lang.Override
    public int getPitSpeedLimit() {
      return pitSpeedLimit_;
    }

    public static final int SECTORS_FIELD_NUMBER = 6;
    private com.google.protobuf.Internal.FloatList sectors_;
    /**
     * <code>repeated float sectors = 6;</code>
     * @return A list containing the sectors.
     */
    @java.lang.Override
    public java.util.List<java.lang.Float>
        getSectorsList() {
      return sectors_;
    }
    /**
     * <code>repeated float sectors = 6;</code>
     * @return The count of sectors.
     */
    public int getSectorsCount() {
      return sectors_.size();
    }
    /**
     * <code>repeated float sectors = 6;</code>
     * @param index The index of the element to return.
     * @return The sectors at the given index.
     */
    public float getSectors(int index) {
      return sectors_.getFloat(index);
    }
    private int sectorsMemoizedSerializedSize = -1;

    public static final int TOTALTIME_FIELD_NUMBER = 7;
    private float totalTime_;
    /**
     * <code>optional float totalTime = 7;</code>
     * @return Whether the totalTime field is set.
     */
    @java.lang.Override
    public boolean hasTotalTime() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional float totalTime = 7;</code>
     * @return The totalTime.
     */
    @java.lang.Override
    public float getTotalTime() {
      return totalTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, trackId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, trackConfigName_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, numTurns_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, pitSpeedLimit_);
      }
      if (getSectorsList().size() > 0) {
        output.writeUInt32NoTag(50);
        output.writeUInt32NoTag(sectorsMemoizedSerializedSize);
      }
      for (int i = 0; i < sectors_.size(); i++) {
        output.writeFloatNoTag(sectors_.getFloat(i));
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeFloat(7, totalTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, trackId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, trackConfigName_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, numTurns_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, pitSpeedLimit_);
      }
      {
        int dataSize = 0;
        dataSize = 4 * getSectorsList().size();
        size += dataSize;
        if (!getSectorsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        sectorsMemoizedSerializedSize = dataSize;
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, totalTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.landonpatmore.models.Pushable.General)) {
        return super.equals(obj);
      }
      com.landonpatmore.models.Pushable.General other = (com.landonpatmore.models.Pushable.General) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasTrackId() != other.hasTrackId()) return false;
      if (hasTrackId()) {
        if (getTrackId()
            != other.getTrackId()) return false;
      }
      if (hasTrackConfigName() != other.hasTrackConfigName()) return false;
      if (hasTrackConfigName()) {
        if (!getTrackConfigName()
            .equals(other.getTrackConfigName())) return false;
      }
      if (hasNumTurns() != other.hasNumTurns()) return false;
      if (hasNumTurns()) {
        if (getNumTurns()
            != other.getNumTurns()) return false;
      }
      if (hasPitSpeedLimit() != other.hasPitSpeedLimit()) return false;
      if (hasPitSpeedLimit()) {
        if (getPitSpeedLimit()
            != other.getPitSpeedLimit()) return false;
      }
      if (!getSectorsList()
          .equals(other.getSectorsList())) return false;
      if (hasTotalTime() != other.hasTotalTime()) return false;
      if (hasTotalTime()) {
        if (java.lang.Float.floatToIntBits(getTotalTime())
            != java.lang.Float.floatToIntBits(
                other.getTotalTime())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasTrackId()) {
        hash = (37 * hash) + TRACKID_FIELD_NUMBER;
        hash = (53 * hash) + getTrackId();
      }
      if (hasTrackConfigName()) {
        hash = (37 * hash) + TRACKCONFIGNAME_FIELD_NUMBER;
        hash = (53 * hash) + getTrackConfigName().hashCode();
      }
      if (hasNumTurns()) {
        hash = (37 * hash) + NUMTURNS_FIELD_NUMBER;
        hash = (53 * hash) + getNumTurns();
      }
      if (hasPitSpeedLimit()) {
        hash = (37 * hash) + PITSPEEDLIMIT_FIELD_NUMBER;
        hash = (53 * hash) + getPitSpeedLimit();
      }
      if (getSectorsCount() > 0) {
        hash = (37 * hash) + SECTORS_FIELD_NUMBER;
        hash = (53 * hash) + getSectorsList().hashCode();
      }
      if (hasTotalTime()) {
        hash = (37 * hash) + TOTALTIME_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getTotalTime());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.landonpatmore.models.Pushable.General parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.landonpatmore.models.Pushable.General parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.landonpatmore.models.Pushable.General parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.landonpatmore.models.Pushable.General parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.landonpatmore.models.Pushable.General parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.landonpatmore.models.Pushable.General parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.landonpatmore.models.Pushable.General parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.landonpatmore.models.Pushable.General parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.landonpatmore.models.Pushable.General parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.landonpatmore.models.Pushable.General parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.landonpatmore.models.Pushable.General parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.landonpatmore.models.Pushable.General parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.landonpatmore.models.Pushable.General prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.landonpatmore.models.General}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.landonpatmore.models.General)
        com.landonpatmore.models.Pushable.GeneralOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.landonpatmore.models.Pushable.internal_static_com_landonpatmore_models_General_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.landonpatmore.models.Pushable.internal_static_com_landonpatmore_models_General_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.landonpatmore.models.Pushable.General.class, com.landonpatmore.models.Pushable.General.Builder.class);
      }

      // Construct using com.landonpatmore.models.Pushable.General.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        trackId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        trackConfigName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        numTurns_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        pitSpeedLimit_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        sectors_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000020);
        totalTime_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.landonpatmore.models.Pushable.internal_static_com_landonpatmore_models_General_descriptor;
      }

      @java.lang.Override
      public com.landonpatmore.models.Pushable.General getDefaultInstanceForType() {
        return com.landonpatmore.models.Pushable.General.getDefaultInstance();
      }

      @java.lang.Override
      public com.landonpatmore.models.Pushable.General build() {
        com.landonpatmore.models.Pushable.General result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.landonpatmore.models.Pushable.General buildPartial() {
        com.landonpatmore.models.Pushable.General result = new com.landonpatmore.models.Pushable.General(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.trackId_ = trackId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.trackConfigName_ = trackConfigName_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.numTurns_ = numTurns_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.pitSpeedLimit_ = pitSpeedLimit_;
          to_bitField0_ |= 0x00000010;
        }
        if (((bitField0_ & 0x00000020) != 0)) {
          sectors_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.sectors_ = sectors_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.totalTime_ = totalTime_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.landonpatmore.models.Pushable.General) {
          return mergeFrom((com.landonpatmore.models.Pushable.General)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.landonpatmore.models.Pushable.General other) {
        if (other == com.landonpatmore.models.Pushable.General.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasTrackId()) {
          setTrackId(other.getTrackId());
        }
        if (other.hasTrackConfigName()) {
          bitField0_ |= 0x00000004;
          trackConfigName_ = other.trackConfigName_;
          onChanged();
        }
        if (other.hasNumTurns()) {
          setNumTurns(other.getNumTurns());
        }
        if (other.hasPitSpeedLimit()) {
          setPitSpeedLimit(other.getPitSpeedLimit());
        }
        if (!other.sectors_.isEmpty()) {
          if (sectors_.isEmpty()) {
            sectors_ = other.sectors_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureSectorsIsMutable();
            sectors_.addAll(other.sectors_);
          }
          onChanged();
        }
        if (other.hasTotalTime()) {
          setTotalTime(other.getTotalTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.landonpatmore.models.Pushable.General parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.landonpatmore.models.Pushable.General) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int trackId_ ;
      /**
       * <code>optional int32 trackId = 2;</code>
       * @return Whether the trackId field is set.
       */
      @java.lang.Override
      public boolean hasTrackId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 trackId = 2;</code>
       * @return The trackId.
       */
      @java.lang.Override
      public int getTrackId() {
        return trackId_;
      }
      /**
       * <code>optional int32 trackId = 2;</code>
       * @param value The trackId to set.
       * @return This builder for chaining.
       */
      public Builder setTrackId(int value) {
        bitField0_ |= 0x00000002;
        trackId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 trackId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTrackId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        trackId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object trackConfigName_ = "";
      /**
       * <code>optional string trackConfigName = 3;</code>
       * @return Whether the trackConfigName field is set.
       */
      public boolean hasTrackConfigName() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string trackConfigName = 3;</code>
       * @return The trackConfigName.
       */
      public java.lang.String getTrackConfigName() {
        java.lang.Object ref = trackConfigName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          trackConfigName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string trackConfigName = 3;</code>
       * @return The bytes for trackConfigName.
       */
      public com.google.protobuf.ByteString
          getTrackConfigNameBytes() {
        java.lang.Object ref = trackConfigName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          trackConfigName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string trackConfigName = 3;</code>
       * @param value The trackConfigName to set.
       * @return This builder for chaining.
       */
      public Builder setTrackConfigName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        trackConfigName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string trackConfigName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTrackConfigName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        trackConfigName_ = getDefaultInstance().getTrackConfigName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string trackConfigName = 3;</code>
       * @param value The bytes for trackConfigName to set.
       * @return This builder for chaining.
       */
      public Builder setTrackConfigNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000004;
        trackConfigName_ = value;
        onChanged();
        return this;
      }

      private int numTurns_ ;
      /**
       * <code>optional int32 numTurns = 4;</code>
       * @return Whether the numTurns field is set.
       */
      @java.lang.Override
      public boolean hasNumTurns() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 numTurns = 4;</code>
       * @return The numTurns.
       */
      @java.lang.Override
      public int getNumTurns() {
        return numTurns_;
      }
      /**
       * <code>optional int32 numTurns = 4;</code>
       * @param value The numTurns to set.
       * @return This builder for chaining.
       */
      public Builder setNumTurns(int value) {
        bitField0_ |= 0x00000008;
        numTurns_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 numTurns = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumTurns() {
        bitField0_ = (bitField0_ & ~0x00000008);
        numTurns_ = 0;
        onChanged();
        return this;
      }

      private int pitSpeedLimit_ ;
      /**
       * <code>optional int32 pitSpeedLimit = 5;</code>
       * @return Whether the pitSpeedLimit field is set.
       */
      @java.lang.Override
      public boolean hasPitSpeedLimit() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 pitSpeedLimit = 5;</code>
       * @return The pitSpeedLimit.
       */
      @java.lang.Override
      public int getPitSpeedLimit() {
        return pitSpeedLimit_;
      }
      /**
       * <code>optional int32 pitSpeedLimit = 5;</code>
       * @param value The pitSpeedLimit to set.
       * @return This builder for chaining.
       */
      public Builder setPitSpeedLimit(int value) {
        bitField0_ |= 0x00000010;
        pitSpeedLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pitSpeedLimit = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPitSpeedLimit() {
        bitField0_ = (bitField0_ & ~0x00000010);
        pitSpeedLimit_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.FloatList sectors_ = emptyFloatList();
      private void ensureSectorsIsMutable() {
        if (!((bitField0_ & 0x00000020) != 0)) {
          sectors_ = mutableCopy(sectors_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated float sectors = 6;</code>
       * @return A list containing the sectors.
       */
      public java.util.List<java.lang.Float>
          getSectorsList() {
        return ((bitField0_ & 0x00000020) != 0) ?
                 java.util.Collections.unmodifiableList(sectors_) : sectors_;
      }
      /**
       * <code>repeated float sectors = 6;</code>
       * @return The count of sectors.
       */
      public int getSectorsCount() {
        return sectors_.size();
      }
      /**
       * <code>repeated float sectors = 6;</code>
       * @param index The index of the element to return.
       * @return The sectors at the given index.
       */
      public float getSectors(int index) {
        return sectors_.getFloat(index);
      }
      /**
       * <code>repeated float sectors = 6;</code>
       * @param index The index to set the value at.
       * @param value The sectors to set.
       * @return This builder for chaining.
       */
      public Builder setSectors(
          int index, float value) {
        ensureSectorsIsMutable();
        sectors_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float sectors = 6;</code>
       * @param value The sectors to add.
       * @return This builder for chaining.
       */
      public Builder addSectors(float value) {
        ensureSectorsIsMutable();
        sectors_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float sectors = 6;</code>
       * @param values The sectors to add.
       * @return This builder for chaining.
       */
      public Builder addAllSectors(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureSectorsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sectors_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float sectors = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSectors() {
        sectors_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }

      private float totalTime_ ;
      /**
       * <code>optional float totalTime = 7;</code>
       * @return Whether the totalTime field is set.
       */
      @java.lang.Override
      public boolean hasTotalTime() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional float totalTime = 7;</code>
       * @return The totalTime.
       */
      @java.lang.Override
      public float getTotalTime() {
        return totalTime_;
      }
      /**
       * <code>optional float totalTime = 7;</code>
       * @param value The totalTime to set.
       * @return This builder for chaining.
       */
      public Builder setTotalTime(float value) {
        bitField0_ |= 0x00000040;
        totalTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float totalTime = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        totalTime_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.landonpatmore.models.General)
    }

    // @@protoc_insertion_point(class_scope:com.landonpatmore.models.General)
    private static final com.landonpatmore.models.Pushable.General DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.landonpatmore.models.Pushable.General();
    }

    public static com.landonpatmore.models.Pushable.General getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<General>
        PARSER = new com.google.protobuf.AbstractParser<General>() {
      @java.lang.Override
      public General parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new General(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<General> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<General> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.landonpatmore.models.Pushable.General getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_landonpatmore_models_General_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_landonpatmore_models_General_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016pushable.proto\022\030com.landonpatmore.mode" +
      "ls\"\202\002\n\007General\022\021\n\004name\030\001 \001(\tH\000\210\001\001\022\024\n\007tra" +
      "ckId\030\002 \001(\005H\001\210\001\001\022\034\n\017trackConfigName\030\003 \001(\t" +
      "H\002\210\001\001\022\025\n\010numTurns\030\004 \001(\005H\003\210\001\001\022\032\n\rpitSpeed" +
      "Limit\030\005 \001(\005H\004\210\001\001\022\017\n\007sectors\030\006 \003(\002\022\026\n\ttot" +
      "alTime\030\007 \001(\002H\005\210\001\001B\007\n\005_nameB\n\n\010_trackIdB\022" +
      "\n\020_trackConfigNameB\013\n\t_numTurnsB\020\n\016_pitS" +
      "peedLimitB\014\n\n_totalTimeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_landonpatmore_models_General_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_landonpatmore_models_General_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_landonpatmore_models_General_descriptor,
        new java.lang.String[] { "Name", "TrackId", "TrackConfigName", "NumTurns", "PitSpeedLimit", "Sectors", "TotalTime", "Name", "TrackId", "TrackConfigName", "NumTurns", "PitSpeedLimit", "TotalTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
