# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logger_update.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13logger_update.proto\x12\x1f\x63om.landonpatmore.models.logger\"\xa4\x02\n\rLoggerGeneral\x12\x11\n\x04tick\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07trackId\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x1c\n\x0ftrackConfigName\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x15\n\x08numTurns\x18\x05 \x01(\x05H\x04\x88\x01\x01\x12\x1a\n\rpitSpeedLimit\x18\x06 \x01(\x05H\x05\x88\x01\x01\x12\x0f\n\x07sectors\x18\x07 \x03(\x02\x12\x16\n\ttotalTime\x18\x08 \x01(\x02H\x06\x88\x01\x01\x42\x07\n\x05_tickB\x07\n\x05_nameB\n\n\x08_trackIdB\x12\n\x10_trackConfigNameB\x0b\n\t_numTurnsB\x10\n\x0e_pitSpeedLimitB\x0c\n\n_totalTimeb\x06proto3')



_LOGGERGENERAL = DESCRIPTOR.message_types_by_name['LoggerGeneral']
LoggerGeneral = _reflection.GeneratedProtocolMessageType('LoggerGeneral', (_message.Message,), {
  'DESCRIPTOR' : _LOGGERGENERAL,
  '__module__' : 'logger_update_pb2'
  # @@protoc_insertion_point(class_scope:com.landonpatmore.models.logger.LoggerGeneral)
  })
_sym_db.RegisterMessage(LoggerGeneral)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGGERGENERAL._serialized_start=57
  _LOGGERGENERAL._serialized_end=349
# @@protoc_insertion_point(module_scope)
