# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: typed_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13typed_message.proto\x12\x18\x63om.landonpatmore.models\x1a\x19google/protobuf/any.proto\"\xc9\x02\n\x0cTypedMessage\x12>\n\x04type\x18\x01 \x01(\x0e\x32+.com.landonpatmore.models.TypedMessage.TypeH\x00\x88\x01\x01\x12*\n\x07message\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyH\x01\x88\x01\x01\"\xb7\x01\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x11\n\rLOGGER_STREAM\x10\x01\x12\x11\n\rLOGGER_UPDATE\x10\x02\x12\x19\n\x15VIEWER_GENERAL_UPDATE\x10\x03\x12\x15\n\x11VIEWER_CAR_UPDATE\x10\x04\x12\x1d\n\x19VIEWER_COMPETITORS_UPDATE\x10\x05\x12\x18\n\x14VIEWER_RACERS_UPDATE\x10\x06\x12\x11\n\rVIEWER_STREAM\x10\x07\x42\x07\n\x05_typeB\n\n\x08_messageb\x06proto3')



_TYPEDMESSAGE = DESCRIPTOR.message_types_by_name['TypedMessage']
_TYPEDMESSAGE_TYPE = _TYPEDMESSAGE.enum_types_by_name['Type']
TypedMessage = _reflection.GeneratedProtocolMessageType('TypedMessage', (_message.Message,), {
  'DESCRIPTOR' : _TYPEDMESSAGE,
  '__module__' : 'typed_message_pb2'
  # @@protoc_insertion_point(class_scope:com.landonpatmore.models.TypedMessage)
  })
_sym_db.RegisterMessage(TypedMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TYPEDMESSAGE._serialized_start=77
  _TYPEDMESSAGE._serialized_end=406
  _TYPEDMESSAGE_TYPE._serialized_start=202
  _TYPEDMESSAGE_TYPE._serialized_end=385
# @@protoc_insertion_point(module_scope)
