//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protobufs/pushable.proto

package pushable;

@kotlin.jvm.JvmSynthetic
public inline fun general(block: pushable.GeneralKt.Dsl.() -> kotlin.Unit): pushable.Pushable.General =
  pushable.GeneralKt.Dsl._create(pushable.Pushable.General.newBuilder()).apply { block() }._build()
public object GeneralKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pushable.Pushable.General.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pushable.Pushable.General.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pushable.Pushable.General = _builder.build()

    /**
     * <code>optional string name = 1;</code>
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>optional string name = 1;</code>
     */
    public fun clearName() {
      _builder.clearName()
    }
    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    public fun hasName(): kotlin.Boolean {
      return _builder.hasName()
    }

    /**
     * <code>optional int32 trackId = 2;</code>
     */
    public var trackId: kotlin.Int
      @JvmName("getTrackId")
      get() = _builder.getTrackId()
      @JvmName("setTrackId")
      set(value) {
        _builder.setTrackId(value)
      }
    /**
     * <code>optional int32 trackId = 2;</code>
     */
    public fun clearTrackId() {
      _builder.clearTrackId()
    }
    /**
     * <code>optional int32 trackId = 2;</code>
     * @return Whether the trackId field is set.
     */
    public fun hasTrackId(): kotlin.Boolean {
      return _builder.hasTrackId()
    }

    /**
     * <code>optional string trackConfigName = 3;</code>
     */
    public var trackConfigName: kotlin.String
      @JvmName("getTrackConfigName")
      get() = _builder.getTrackConfigName()
      @JvmName("setTrackConfigName")
      set(value) {
        _builder.setTrackConfigName(value)
      }
    /**
     * <code>optional string trackConfigName = 3;</code>
     */
    public fun clearTrackConfigName() {
      _builder.clearTrackConfigName()
    }
    /**
     * <code>optional string trackConfigName = 3;</code>
     * @return Whether the trackConfigName field is set.
     */
    public fun hasTrackConfigName(): kotlin.Boolean {
      return _builder.hasTrackConfigName()
    }

    /**
     * <code>optional int32 numTurns = 4;</code>
     */
    public var numTurns: kotlin.Int
      @JvmName("getNumTurns")
      get() = _builder.getNumTurns()
      @JvmName("setNumTurns")
      set(value) {
        _builder.setNumTurns(value)
      }
    /**
     * <code>optional int32 numTurns = 4;</code>
     */
    public fun clearNumTurns() {
      _builder.clearNumTurns()
    }
    /**
     * <code>optional int32 numTurns = 4;</code>
     * @return Whether the numTurns field is set.
     */
    public fun hasNumTurns(): kotlin.Boolean {
      return _builder.hasNumTurns()
    }

    /**
     * <code>optional int32 pitSpeedLimit = 5;</code>
     */
    public var pitSpeedLimit: kotlin.Int
      @JvmName("getPitSpeedLimit")
      get() = _builder.getPitSpeedLimit()
      @JvmName("setPitSpeedLimit")
      set(value) {
        _builder.setPitSpeedLimit(value)
      }
    /**
     * <code>optional int32 pitSpeedLimit = 5;</code>
     */
    public fun clearPitSpeedLimit() {
      _builder.clearPitSpeedLimit()
    }
    /**
     * <code>optional int32 pitSpeedLimit = 5;</code>
     * @return Whether the pitSpeedLimit field is set.
     */
    public fun hasPitSpeedLimit(): kotlin.Boolean {
      return _builder.hasPitSpeedLimit()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SectorsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated float sectors = 6;</code>
     */
     public val sectors: com.google.protobuf.kotlin.DslList<kotlin.Float, SectorsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getSectorsList()
      )
    /**
     * <code>repeated float sectors = 6;</code>
     * @param value The sectors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSectors")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Float, SectorsProxy>.add(value: kotlin.Float) {
      _builder.addSectors(value)
    }/**
     * <code>repeated float sectors = 6;</code>
     * @param value The sectors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSectors")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Float, SectorsProxy>.plusAssign(value: kotlin.Float) {
      add(value)
    }/**
     * <code>repeated float sectors = 6;</code>
     * @param values The sectors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSectors")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Float, SectorsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Float>) {
      _builder.addAllSectors(values)
    }/**
     * <code>repeated float sectors = 6;</code>
     * @param values The sectors to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSectors")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Float, SectorsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Float>) {
      addAll(values)
    }/**
     * <code>repeated float sectors = 6;</code>
     * @param index The index to set the value at.
     * @param value The sectors to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSectors")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Float, SectorsProxy>.set(index: kotlin.Int, value: kotlin.Float) {
      _builder.setSectors(index, value)
    }/**
     * <code>repeated float sectors = 6;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSectors")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Float, SectorsProxy>.clear() {
      _builder.clearSectors()
    }
    /**
     * <code>optional float totalTime = 7;</code>
     */
    public var totalTime: kotlin.Float
      @JvmName("getTotalTime")
      get() = _builder.getTotalTime()
      @JvmName("setTotalTime")
      set(value) {
        _builder.setTotalTime(value)
      }
    /**
     * <code>optional float totalTime = 7;</code>
     */
    public fun clearTotalTime() {
      _builder.clearTotalTime()
    }
    /**
     * <code>optional float totalTime = 7;</code>
     * @return Whether the totalTime field is set.
     */
    public fun hasTotalTime(): kotlin.Boolean {
      return _builder.hasTotalTime()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun pushable.Pushable.General.copy(block: pushable.GeneralKt.Dsl.() -> kotlin.Unit): pushable.Pushable.General =
  pushable.GeneralKt.Dsl._create(this.toBuilder()).apply { block() }._build()
